export type UserRole = 'Director' | 'Admin' | 'User';
export type TaskStatus = 'Pending' | 'Under Review' | 'Completed' | 'Rejected';

export interface Profile {
  id: string;
  employee_id: string;
  full_name: string;
  role: UserRole;
  total_tokens: number;
  is_temporary_password: boolean;
  // Personal info fields
  date_of_birth: string | null;
  email: string | null;
  phone: string | null;
  linkedin_url: string | null;
  github_url: string | null;
  resume_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface Task {
  id: string;
  created_by: string;
  assigned_to: string;
  title: string;
  description: string;
  deadline: string;
  tokens: number;
  status: TaskStatus;
  submitted_at: string | null;
  approved_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface PointsLog {
  id: string;
  user_id: string;
  task_id: string;
  tokens_awarded: number;
  reason: string;
  created_at: string;
}

// employee_id is optional on insert (auto-generated by trigger)
export type ProfileInsert = Omit<Profile, 'created_at' | 'updated_at' | 'employee_id'> & {
  employee_id?: string;
};
export type ProfileUpdate = Partial<Omit<Profile, 'id' | 'created_at'>>;
export type TaskInsert = Omit<Task, 'id' | 'created_at' | 'updated_at' | 'submitted_at' | 'approved_at'> & {
  submitted_at?: string | null;
  approved_at?: string | null;
};
export type TaskUpdate = Partial<Omit<Task, 'id' | 'created_at'>>;
export type PointsLogInsert = Omit<PointsLog, 'id' | 'created_at'>;

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: Profile;
        Insert: ProfileInsert;
        Update: ProfileUpdate;
      };
      tasks: {
        Row: Task;
        Insert: TaskInsert;
        Update: TaskUpdate;
      };
      points_log: {
        Row: PointsLog;
        Insert: PointsLogInsert;
        Update: Partial<PointsLog>;
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      increment_tokens: {
        Args: { user_id: string; amount: number };
        Returns: undefined;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

