import { create } from 'zustand';
import { supabase } from '../lib/supabase';
import type { Profile } from '../types/database';

interface UserState {
  users: Profile[];
  leaderboard: Profile[];
  loading: boolean;
  fetchUsers: () => Promise<void>;
  fetchLeaderboard: () => Promise<void>;
  createUser: (email: string, password: string, fullName: string, role: 'Admin' | 'User') => Promise<{ error: string | null; employeeId?: string }>;
  deleteUser: (userId: string) => Promise<{ error: string | null }>;
}

export const useUserStore = create<UserState>((set, get) => ({
  users: [],
  leaderboard: [],
  loading: false,

  fetchUsers: async () => {
    set({ loading: true });
    
    const { data, error } = await supabase
      .from('profiles')
      .select('*')
      .order('created_at', { ascending: false });
    
    if (!error && data) {
      set({ users: data });
    }
    
    set({ loading: false });
  },

  fetchLeaderboard: async () => {
    const { data, error } = await supabase
      .from('profiles')
      .select('*')
      .eq('role', 'User')
      .order('total_tokens', { ascending: false })
      .limit(50);
    
    if (!error && data) {
      set({ leaderboard: data });
    }
  },

  createUser: async (email: string, password: string, fullName: string, role: 'Admin' | 'User') => {
    // Create auth user via admin API (this would typically be a server-side function)
    // For demo, we'll use the signUp method and then update the profile
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email,
      password,
      options: {
        data: {
          full_name: fullName,
          role,
        },
      },
    });

    if (authError) {
      return { error: authError.message };
    }

    if (!authData.user) {
      return { error: 'Failed to create user' };
    }

    // Create profile - employee_id is auto-generated by database trigger
    const { data: profileData, error: profileError } = await supabase
      .from('profiles')
      .insert({
        id: authData.user.id,
        full_name: fullName,
        role,
        total_tokens: 0,
        is_temporary_password: true,
      })
      .select('employee_id')
      .single();

    if (profileError) {
      return { error: profileError.message };
    }

    await get().fetchUsers();
    return { error: null, employeeId: profileData?.employee_id };
  },

  deleteUser: async (userId: string) => {
    // Note: Deleting auth user requires admin privileges
    // This would typically be handled by a server-side function
    const { error } = await supabase
      .from('profiles')
      .delete()
      .eq('id', userId);

    if (error) {
      return { error: error.message };
    }

    set((state) => ({
      users: state.users.filter((u) => u.id !== userId),
    }));

    return { error: null };
  },
}));
